const Map<String, dynamic> stringDict = {
  "Türkçe": {
    "code": "tr",
    "autotranslate": "Blog Türkçe dilinde",
    "originalLang": "Blog Türkçe dilinde",
    "translating": "Çeviriliyor...",
    "search": "Başlık Ara",
    "title": "Fatih Koparan'ın Galaksi Rehberi",
    "about": "Hakkında",
    "map": "Harita",
    "blog": "Blog",
    "donate": "Bağış Yap",
    "donateText":"Darüşşafaka Cemiyeti, babalarını kaybetmiş ihtiyaç sahibi yetenekli çocuklara eğitimde eşit fırsat sağlamak amacıyla 1863 yılında kurulmuştur. O tarihten beri “Eğitimde Eşit Fırsat” misyonuyla varlığını sürdürmektedir. Okulu finanse etmek amacıyla bağışlarla kaynak toplayan 158 yıllık Cemiyetimiz, 14 Nisan 2012 tarihinde tüzüğünü değiştirerek Darüşşafaka Okullarının kapılarını annelerini kaybetmiş öğrenciler için de açmıştır. Bugün Darüşşafaka, bir veya her iki ebeveynini kaybetmiş ihtiyaç sahibi yetenekli öğrenciler için daha iyi bir gelecek yaratmaktadır. On yaşındaki öğrencileri davet eden Cemiyetimiz, öğrencinin beşinci sınıfından lise sonuna kadar tam burs ve yatılı eğitim imkanı sağlamaktadır. Dünya standartlarında bir eğitim fırsatı sunulan öğrenciler, topluma karşı sorumluluk duyan, kendine güvenen, düşünen, sorgulayan ve meraklı bireyler olarak yeni bir hayata adım atmaktadırlar.",
    "aboutText":
    "Herkese selamlar.\n\nGloballeşen dünyada artık her şey aynılaşmaya başladı. El Salvador'dan Japonya'ya, Ürdün'den Cape Town'a aynı markalar, aynı evler, aynı hikayeler, aynı düşünen insanlar etrafımızı sardı. Bu kanalda aynılaşan dünyamızın kıyısında köşesinde kalmış farklılıkları, yerel lezzetleri, sokak yemeklerini, ülkelerin tarihini, uzaklardaki kabileleri, ülkelerin aydınlık tarafları kadar karanlık taraflarını keşfetmeye çalışıyorum. Tüm kanalımızın gelirlerini de sayenizde öğrencilere burs veriyorum. Dekontları da paylaşıyorum. Bu kanal hepimizin. O sebeple takip edip destek olursanız sevinirim.\n\nSevgiler.",
  },
  "English": {
    "code": "en",
    "autotranslate": "Auto Translate All Entries to The English",
    "originalLang": "Show Original Language",
    "translating": "Translating...",
    "search": "Search Title",
    "title": "Fatih Koparan's Guide to the Galaxy",
    "about": "About",
    "map": "Map",
    "blog": "Blog",
    "donate": "Donate",
    "donateText":"Darüşşafaka Society was founded in 1863 with the aim of providing  equal opportunity in education to needy, talented children who had lost their fathers. Since then, it has maintained its presence with this mission of 'Equal Opportunity in Education'. Our 158-year old Society, whose role is to raise funds via donations to finance the school, amended its statutes on 14 April 2012 and opened the doors of Darüşşafaka Schools to also include students who have lost their mothers. Today, Darüşşafaka creates a better future for needy, talented students with one or no parents. Inviting students at the age of ten, the Society provides full scholarship and boarding from a student’s fifth year through to the end of high school. Given an opportunity for a world-class education, students are able to embark on a new life as self confident, thinking, inquiring, and curious individuals who feel responsible for the community.",
    "aboutText":
    "Hello everyone.\n\nIn our globalizing world, everything is starting to become the same. From El Salvador to Japan, from Jordan to Cape Town, the same brands, the same houses, the same stories, and the same thinking people surround us. On this channel, I try to explore the differences, local flavors, street foods, the history of countries, distant tribes, and both the bright and dark sides of countries that remain on the edges and corners of our homogenizing world. Thanks to you, I give all the channel’s income as scholarships to students. I also share the receipts. This channel belongs to all of us. So I would be happy if you follow and support it.\n\nRegards.",
  },
  "Español": {
    "code": "es",
    "autotranslate": "Traducir automáticamente todas las entradas al español",
    "originalLang": "Mostrar idioma original",
    "translating": "Traduciendo...",
    "search": "Buscar título",
    "title": "La Guía de la Galaxia de Fatih Koparan",
    "about": "Acerca de",
    "map": "Mapa",
    "blog": "Blog",
    "donate": "Donar",
    "donateText": "La Sociedad Darüşşafaka fue fundada en 1863 con el objetivo de proporcionar igualdad de oportunidades educativas a niños necesitados y talentosos que habían perdido a sus padres. Desde entonces, ha mantenido su presencia con esta misión de “Igualdad de Oportunidades en la Educación”. Nuestra Sociedad de 158 años, cuyo papel es recaudar fondos mediante donaciones para financiar la escuela, modificó sus estatutos el 14 de abril de 2012 y abrió las puertas de las escuelas Darüşşafaka para incluir también a estudiantes que han perdido a sus madres. Hoy en día, Darüşşafaka crea un futuro mejor para estudiantes necesitados y talentosos con uno o ningún padre. Invitando a estudiantes a la edad de diez años, la Sociedad proporciona becas completas y residencia desde el quinto año de estudiante hasta el final de la escuela secundaria. Con la oportunidad de una educación de clase mundial, los estudiantes pueden embarcarse en una nueva vida como individuos seguros de sí mismos, pensadores, inquisitivos y curiosos que sienten responsabilidad por la comunidad.",
    "aboutText":
    "Hola a todos.\n\nEn nuestro mundo globalizado, todo está empezando a ser igual. Desde El Salvador hasta Japón, desde Jordania hasta Ciudad del Cabo, las mismas marcas, las mismas casas, las mismas historias y las mismas personas pensantes nos rodean. En este canal, trato de explorar las diferencias, los sabores locales, la comida callejera, la historia de los países, las tribus lejanas y tanto los lados brillantes como oscuros de los países que permanecen en los bordes y rincones de nuestro mundo homogeneizado. Gracias a ustedes, doy todos los ingresos del canal como becas a estudiantes. También comparto los recibos. Este canal es de todos nosotros. Así que me alegraría que lo sigan y apoyen.\n\nSaludos.",
  },
  "Français": {
    "code": "fr",
    "autotranslate": "Traduire automatiquement toutes les entrées en français",
    "originalLang": "Afficher la langue originale",
    "translating": "Traduction en cours...",
    "search": "Rechercher un titre",
    "title": "Le Guide de la Galaxie de Fatih Koparan",
    "about": "À propos",
    "map": "Carte",
    "blog": "Blog",
    "donate": "Faire un don",
    "donateText":"La Société Darüşşafaka a été fondée en 1863 dans le but de fournir des chances égales en éducation aux enfants talentueux dans le besoin ayant perdu leur père. Depuis lors, elle maintient sa présence avec cette mission d’« égalité des chances en éducation ». Notre Société vieille de 158 ans, dont le rôle est de collecter des fonds via des dons pour financer l’école, a modifié ses statuts le 14 avril 2012 et a ouvert les portes des écoles Darüşşafaka aux élèves ayant perdu leur mère. Aujourd’hui, Darüşşafaka crée un avenir meilleur pour les élèves talentueux et nécessiteux ayant un ou aucun parent. Invitant les élèves à l’âge de dix ans, la Société offre une bourse complète et un internat à partir de la cinquième année jusqu’à la fin du lycée. Offerts une éducation de classe mondiale, les élèves peuvent commencer une nouvelle vie en tant qu’individus confiants, réfléchis, curieux et responsables envers la communauté.",
    "aboutText":
    "Bonjour à tous.\n\nDans notre monde mondialisé, tout commence à devenir pareil. D'El Salvador au Japon, de la Jordanie au Cap, les mêmes marques, les mêmes maisons, les mêmes histoires et les mêmes personnes réfléchies nous entourent. Sur cette chaîne, j'essaie d'explorer les différences, les saveurs locales, la nourriture de rue, l'histoire des pays, les tribus lointaines, ainsi que les côtés lumineux et sombres des pays qui restent aux marges de notre monde homogénéisé. Grâce à vous, je donne tous les revenus de la chaîne en bourses aux étudiants. Je partage aussi les reçus. Cette chaîne appartient à nous tous. Je serais donc heureux que vous la suiviez et la souteniez.\n\nCordialement.",
  },
  "Deutsch": {
    "code": "de",
    "autotranslate": "Automatisch alle Einträge ins Deutsche übersetzen",
    "originalLang": "Originalsprache anzeigen",
    "translating": "Übersetzen...",
    "search": "Titel suchen",
    "title": "Fatih Koparans Galaxieführer",
    "about": "Über",
    "map": "Karte",
    "blog": "Blog",
    "donate": "Spenden",
    "donateText":"Die Darüşşafaka-Gesellschaft wurde 1863 gegründet, um bedürftigen, talentierten Kindern, die ihre Väter verloren hatten, gleiche Bildungschancen zu bieten. Seitdem besteht sie mit der Mission „Gleiche Bildungschancen“ fort. Unsere 158 Jahre alte Gesellschaft, deren Aufgabe es ist, durch Spenden Mittel für die Schule zu beschaffen, änderte am 14. April 2012 ihre Satzung und öffnete die Türen der Darüşşafaka-Schulen auch für Schüler, die ihre Mütter verloren haben. Heute schafft Darüşşafaka eine bessere Zukunft für bedürftige, talentierte Schüler mit einem oder ohne Elternteil. Die Gesellschaft nimmt Schüler im Alter von zehn Jahren auf und bietet von der fünften Klasse bis zum Ende der High School ein Vollstipendium und Internatsunterbringung. Mit der Chance auf eine erstklassige Ausbildung können die Schüler ein neues Leben als selbstbewusste, denkende, fragende und neugierige Individuen beginnen, die sich ihrer Verantwortung gegenüber der Gemeinschaft bewusst sind.",
    "aboutText":
    "Hallo zusammen.\n\nIn unserer globalisierten Welt beginnt alles, gleich zu werden. Von El Salvador bis Japan, von Jordanien bis Kapstadt umgeben uns dieselben Marken, dieselben Häuser, dieselben Geschichten und dieselben denkenden Menschen. In diesem Kanal versuche ich, die Unterschiede, lokalen Geschmäcker, Straßenessen, die Geschichte der Länder, ferne Stämme und sowohl die hellen als auch die dunklen Seiten der Länder zu erkunden, die am Rand unserer sich vereinheitlichenden Welt bleiben. Dank euch gebe ich alle Einnahmen des Kanals als Stipendien an Studenten weiter. Ich teile auch die Belege. Dieser Kanal gehört uns allen. Deshalb würde ich mich freuen, wenn ihr folgt und unterstützt.\n\nViele Grüße.",
  },
  "العربية": {
    "code": "ar",
    "autotranslate": "ترجمة تلقائية لجميع الإدخالات إلى العربية",
    "originalLang": "عرض اللغة الأصلية",
    "translating": "جاري الترجمة...",
    "search": "بحث عن عنوان",
    "title": "دليل فاتح كوباران للمجرة",
    "about": "حول",
    "map": "خريطة",
    "blog": "مدونة",
    "donate": "تبرع",
    "donateText":"تأسست جمعية دار الشفاقة في عام 1863 بهدف توفير فرص متساوية في التعليم للأطفال المحتاجين والموهوبين الذين فقدوا آباءهم. ومنذ ذلك الحين، حافظت على وجودها مع هذه الرسالة المتمثلة في 'توفير فرص متساوية في التعليم'. جمعية عمرها 158 عامًا، وتتمثل مهمتها في جمع الأموال عبر التبرعات لتمويل المدرسة، قامت بتعديل نظامها الأساسي في 14 أبريل 2012 وفتحت أبواب مدارس دار الشفاقة لتشمل أيضًا الطلاب الذين فقدوا أمهاتهم. اليوم، تخلق دار الشفاقة مستقبلاً أفضل للطلاب المحتاجين والموهوبين الذين لديهم أحد الوالدين أو لا أحد منهما. تدعو الجمعية الطلاب في سن العاشرة، وتوفر منحة دراسية كاملة وإقامة من السنة الخامسة حتى نهاية المرحلة الثانوية. بفضل فرصة التعليم على مستوى عالمي، يتمكن الطلاب من بدء حياة جديدة كأفراد واثقين من أنفسهم، مفكرين، مستفسرين وفضوليين يشعرون بالمسؤولية تجاه المجتمع.",
    "aboutText":
    "مرحباً بالجميع.\n\nفي عالمنا المعولم، بدأ كل شيء يصبح متشابهاً. من السلفادور إلى اليابان، ومن الأردن إلى كيب تاون، تحيط بنا نفس العلامات التجارية، ونفس المنازل، ونفس القصص، ونفس الأشخاص المفكرين. في هذه القناة، أحاول استكشاف الاختلافات، والنكهات المحلية، وأطعمة الشوارع، وتاريخ البلدان، والقبائل البعيدة، والجوانب المضيئة والمظلمة للبلدان التي تبقى على أطراف عالمنا المتجانس. بفضلكم، أقدم كل دخل القناة كمنح دراسية للطلاب. كما أشارك الإيصالات. هذه القناة تخصنا جميعاً. لذلك سأكون سعيداً إذا تابعتم ودعمتم القناة.\n\nتحياتي.",
  },
  "Português": {
    "code": "pt",
    "autotranslate": "Traduzir automaticamente todas as entradas para o português",
    "originalLang": "Mostrar idioma original",
    "translating": "Traduzindo...",
    "search": "Pesquisar título",
    "title": "O Guia Galáctico de Fatih Koparan",
    "about": "Sobre",
    "map": "Mapa",
    "blog": "Blog",
    "donate": "Doar",
    "donateText": "A Sociedade Darüşşafaka foi fundada em 1863 com o objetivo de proporcionar igualdade de oportunidades na educação a crianças talentosas e carentes que perderam seus pais. Desde então, manteve-se fiel à sua missão de “Igualdade de Oportunidades na Educação”. Com 158 anos de história, a Sociedade arrecada fundos por meio de doações para financiar a escola. Em 14 de abril de 2012, alterou seu estatuto para incluir também alunos que perderam suas mães. Hoje, a Darüşşafaka cria um futuro melhor para alunos talentosos e carentes que perderam um ou ambos os pais. Convida estudantes a partir dos dez anos e oferece bolsa integral e ensino com internato do quinto ano até o fim do ensino médio. Com uma educação de nível internacional, os alunos iniciam uma nova vida como indivíduos confiantes, questionadores, pensadores e responsáveis pela comunidade.",
    "aboutText": "Olá a todos.\n\nEm nosso mundo globalizado, tudo está começando a se parecer. De El Salvador ao Japão, da Jordânia à Cidade do Cabo, as mesmas marcas, casas, histórias e pessoas pensantes nos cercam. Neste canal, tento explorar as diferenças, sabores locais, comidas de rua, história dos países, tribos distantes e tanto os lados claros quanto os escuros dos países esquecidos pelo mundo homogêneo. Graças a vocês, todo o rendimento do canal é doado como bolsas de estudo. Também compartilho os comprovantes. Este canal é de todos nós. Ficarei feliz se você seguir e apoiar.\n\nAbraços.",
  },
  "Italiano": {
    "code": "it",
    "autotranslate": "Traduci automaticamente tutte le voci in italiano",
    "originalLang": "Mostra lingua originale",
    "translating": "Traduzione in corso...",
    "search": "Cerca titolo",
    "title": "La Guida Galattica di Fatih Koparan",
    "about": "Chi siamo",
    "map": "Mappa",
    "blog": "Blog",
    "donate": "Dona",
    "donateText": "La Società Darüşşafaka è stata fondata nel 1863 con l'obiettivo di fornire pari opportunità educative ai bambini bisognosi e talentuosi che avevano perso i loro padri. Da allora, continua a esistere con la missione di “Pari Opportunità nell'Istruzione”. La nostra società, vecchia di 158 anni, raccoglie fondi attraverso donazioni per finanziare la scuola. Il 14 aprile 2012 ha modificato il suo statuto per includere anche gli studenti che avevano perso le loro madri. Oggi, Darüşşafaka crea un futuro migliore per studenti talentuosi e bisognosi che hanno perso uno o entrambi i genitori. Accoglie studenti a partire dai dieci anni, offrendo borse di studio complete e istruzione residenziale dal quinto anno alla fine del liceo. Offrendo un'istruzione di livello mondiale, gli studenti possono iniziare una nuova vita come individui fiduciosi, curiosi, pensatori e responsabili verso la comunità.",
    "aboutText": "Ciao a tutti.\n\nNel nostro mondo globalizzato, tutto sta iniziando a diventare uguale. Dall'El Salvador al Giappone, dalla Giordania a Città del Capo, siamo circondati dagli stessi marchi, stesse case, stesse storie e stesse persone pensanti. In questo canale cerco di esplorare le differenze, i sapori locali, il cibo di strada, la storia dei paesi, le tribù lontane e i lati luminosi e oscuri dei paesi che si trovano ai margini del nostro mondo omogeneo. Grazie a voi, dono tutti i proventi del canale come borse di studio agli studenti. Condivido anche le ricevute. Questo canale è di tutti noi. Quindi sarei felice se lo seguiste e lo sosteneste.\n\nUn caro saluto.",
  },
  "Русский": {
    "code": "ru",
    "autotranslate": "Автоматически перевести все записи на русский язык",
    "originalLang": "Показать оригинальный язык",
    "translating": "Перевод...",
    "search": "Поиск по названию",
    "title": "Галактический путеводитель Фатиха Копарана",
    "about": "О канале",
    "map": "Карта",
    "blog": "Блог",
    "donate": "Пожертвовать",
    "donateText": "Общество Дарюшшафака было основано в 1863 году с целью предоставления равных возможностей в образовании для нуждающихся талантливых детей, потерявших своих отцов. С тех пор организация придерживается этой миссии. Наше общество, которому 158 лет, собирает пожертвования для финансирования школы. 14 апреля 2012 года были внесены изменения в устав, чтобы включить учащихся, потерявших матерей. Сегодня Дарюшшафака создает лучшее будущее для талантливых детей, потерявших одного или обоих родителей. С 10 лет учащимся предоставляются полные стипендии и проживание в интернате с 5 класса до окончания школы. С получением образования мирового уровня учащиеся начинают новую жизнь как уверенные в себе, думающие и любознательные личности, чувствующие ответственность перед обществом.",
    "aboutText": "Привет всем.\n\nВ нашем глобализирующемся мире всё становится одинаковым. От Сальвадора до Японии, от Иордании до Кейптауна — те же бренды, те же дома, те же истории и одинаково мыслящие люди окружают нас. На этом канале я стараюсь исследовать различия, местные вкусы, уличную еду, историю стран, далекие племена и как светлые, так и темные стороны стран, находящихся на окраине нашего унифицирующегося мира. Благодаря вам я передаю весь доход с канала на стипендии для студентов. Я также делюсь квитанциями. Этот канал принадлежит всем нам. Поэтому я буду рад, если вы подпишетесь и поддержите его.\n\nС уважением.",
  },
  "中文": {
    "code": "zh",
    "autotranslate": "自动将所有条目翻译成中文",
    "originalLang": "显示原始语言",
    "translating": "翻译中...",
    "search": "搜索标题",
    "title": "法提赫·科帕兰的银河指南",
    "about": "关于",
    "map": "地图",
    "blog": "博客",
    "donate": "捐赠",
    "donateText": "Darüşşafaka协会成立于1863年，旨在为失去父亲的贫困有才华的儿童提供平等的教育机会。自成立以来，该协会始终秉持“教育平等”的使命。这个已有158年历史的协会通过捐赠筹集资金来资助学校。2012年4月14日，协会修改章程，也开始接收失去母亲的学生。如今，Darüşşafaka为失去一位或两位父母的有才华学生创造了更美好的未来。协会招收10岁起的学生，提供从五年级到高中毕业的全额奖学金和住宿教育。获得世界一流教育机会的学生，将以自信、好奇、善于思考与承担社会责任的姿态迈入新生活。",
    "aboutText": "大家好。\n\n在全球化的浪潮中，一切正在变得千篇一律。从萨尔瓦多到日本，从约旦到开普敦，周围都是相同的品牌、相似的房子、雷同的故事和思想。这个频道旨在探索那些被边缘化的差异、当地风味、街头小吃、国家历史、遥远部落，以及各国的光明与黑暗面。感谢大家，我将频道的所有收入用于学生奖学金，也会分享捐赠凭证。这个频道属于我们所有人。如果你愿意关注和支持，我将感激不尽。\n\n致以诚挚问候。",
  },
"日本語": {
"code": "ja",
"autotranslate": "すべてのエントリを日本語に自動翻訳",
"originalLang": "原文を表示",
"translating": "翻訳中…",
"search": "タイトルを検索",
"title": "ファティフ・コパランの銀河ガイド",
"about": "概要",
"map": "地図",
"blog": "ブログ",
"donate": "寄付する",
"donateText": "Darüşşafaka協会は1863年に設立され、父親を失った困窮かつ才能ある子どもたちに教育の機会を平等に提供することを目的としています。それ以来、「教育の機会均等」というミッションを掲げ、158年間にわたって活動を続けています。2012年4月14日、母親を亡くした学生も受け入れるよう定款を改正しました。今日は、Darüşşafakaは一人または両親を失った才能ある学生たちにより良い未来を提供しています。10歳からの学生を迎え、5年生から高校卒業までの全額奨学金と寮を提供しています。世界水準の教育を受けて、学生たちは自信を持ち、考え、探求し、好奇心を持ち、社会に責任を感じる個人として新たな人生を歩み始めます。",
"aboutText": "皆さん、こんにちは。\n\nグローバル化が進む世界では、同一化が進んでいます。エルサルバドルから日本へ、ヨルダンからケープタウンへ、同じブランド、同じ家、同じ物語、同じ考える人々が私たちを取り囲んでいます。このチャンネルでは、均質化する世界の片隅に残る違いや地元の味、ストリートフード、国の歴史、遠くの部族、国の明るい面と暗い面を探求しようとしています。皆さんのおかげで、チャンネルの収益はすべて学生への奨学金に充てています。領収書も公開しています。このチャンネルは私たちみんなのものです。フォローして応援していただけると嬉しいです。\n\nよろしくお願いします。"
},
"한국어": {
"code": "ko",
"autotranslate": "모든 항목을 한국어로 자동 번역",
"originalLang": "원문 언어 보기",
"translating": "번역 중...",
"search": "제목 검색",
"title": "파티흐 코파란의 은하 안내서",
"about": "소개",
"map": "지도",
"blog": "블로그",
"donate": "기부",
"donateText": "Darüşşafaka 협회는 1863년에 설립되어 아버지를 잃은 재능 있는 빈곤 어린이들에게 교육 기회를 평등하게 제공하는 것을 목표로 했습니다. 이후로 ‘교육의 평등 기회’라는 사명을 유지하며 158년간 활동해왔습니다. 2012년 4월 14일에는 어머니를 잃은 학생들도 받을 수 있도록 정관을 개정했습니다. 오늘날 Darüşşafaka는 부모 한쪽 또는 양쪽을 잃은 재능 있는 학생들에게 더 나은 미래를 제공합니다. 만 10세부터 5학년~고등학교 졸업까지 전액 장학금과 기숙사를 지원합니다. 세계 수준의 교육을 통해 학생들은 자신감 있고, 생각하고, 질문하며, 호기심 많고, 공동체를 위한 책임감을 가진 인격체로서 새로운 삶을 시작합니다.",
"aboutText": "여러분 안녕하세요.\n\n세계가 세계화되면서 모든 것이 점점 똑같아지고 있습니다. 엘살바도르에서 일본까지, 요르단에서 케이프타운까지, 같은 브랜드, 같은 집, 같은 이야기, 같은 생각하는 사람들이 우리를 둘러싸고 있습니다. 이 채널에서는 균질화되는 세계의 구석에 남아 있는 차이, 지역의 맛, 거리 음식, 국가의 역사, 먼 부족, 그리고 국가의 밝은 면과 어두운 면을 탐험하고 있습니다. 여러분 덕분에 저는 채널의 모든 수익을 학생들에게 장학금으로 지원하고 있습니다. 영수증도 공유합니다. 이 채널은 우리 모두의 것입니다. 구독하고 응원해 주시면 감사하겠습니다.\n\n감사합니다."
},
"हिन्दी": {
"code": "hi",
"autotranslate": "सभी प्रविष्टियों को हिंदी में स्वचालित अनुवादित करें",
"originalLang": "मूल भाषा दिखाएं",
"translating": "अनुवाद हो रहा है...",
"search": "शीर्षक खोजें",
"title": "फ़तिह़ कोपारान की गैलेक्सीय मार्गदर्शिका",
"about": "बारे में",
"map": "मानचित्र",
"blog": "ब्लॉग",
"donate": "दान करें",
"donateText": "डारुसशाफाका सोसाइटी की स्थापना 1863 में की गई थी, जिसका उद्देश्य पिता को खो चुके प्रतिभाशाली और ज़रूरतमंद बच्चों को समान शिक्षा अवसर प्रदान करना है। तब से, यह 'शिक्षा में समान अवसर' मिशन के साथ अस्तित्व में है। हमारी 158 साल पुरानी सोसाइटी स्कूल को वित्तपोषित करने के लिए दान के माध्यम से धनराशि एकत्र करती है। 14 अप्रैल 2012 को इसके संविधान में संशोधन करके उन छात्रों को भी शामिल किया गया है जिन्होंने अपनी माँ को खोया है। आज डारुसशाफाका प्रतिभाशाली छात्रों के लिए बेहतर भविष्य तैयार करता है जिन्हें एक या दोनों माता-पिता खो चुके हैं। यह दस साल की उम्र से छात्रों को आमंत्रित करता है और पांचवीं कक्षा से हाई स्कूल की समाप्ति तक पूर्ण छात्रवृत्ति और बोर्डिंग प्रदान करता है। विश्व-स्तरीय शिक्षा के अवसर के साथ, छात्र आत्मविश्वास, चिंतनशीलता, जिज्ञासा और समाज के प्रति जिम्मेदारी के साथ नए जीवन की शुरुआत करते हैं।",
"aboutText": "नमस्ते सभी को।\n\nहमारी वैश्विक दुनिया में, सब कुछ एक जैसा होता जा रहा है। अल साल्वाडोर से जापान तक, जॉर्डन से केप टाउन तक, वही ब्रांड, वही घर, वही कहानियाँ, वही सोच वाले लोग हमारा चारों ओर घेरे रहते हैं। इस चैनल पर, मैं उन अंतर को खोजने की कोशिश करता हूँ जो समान प्रवृत्ति की दुनिया के किनारों पर बने हैं: स्थानीय स्वाद, स्ट्रीट फूड, देशों का इतिहास, दूर-दराज के कबीले, और उन देशों के उज्जवल और अंधेरे पक्ष। आपकी मदद से, मैं चैनल की सभी आय छात्रवृत्तियों के रूप में छात्रों को देता हूँ। इसकी रसीदें भी साझा करता हूँ। यह चैनल हम सभी का है। आपके फॉलो और समर्थन से मैं प्रसन्न होऊँगा।\n\nशुभकामनाएँ।"
},
"বাংলা": {
"code": "bn",
"autotranslate": "সকল এন্ট্রিকে বাংলায় স্বয়ংক্রিয় অনুবাদ করুন",
"originalLang": "মূল ভাষা দেখাও",
"translating": "অনুবাদ করা হচ্ছে...",
"search": "টাইটেল অনুসন্ধান",
"title": "ফতিহ্ কোপারানের গ্যালাক্সি গাইড",
"about": "সম্পর্কে",
"map": "মানচিত্র",
"blog": "ব্লগ",
"donate": "দান করুন",
"donateText": "ডারুসশাফাকা সোসাইটি ১৮৬৩ সালে প্রতিষ্ঠিত হয়েছিল, অর্থাৎ পিতামাতাকে হারানো মেধাবী ও আর্থিকভাবে দুর্বল শিশুদের শিক্ষা সমান সুযোগ দেওয়া। 'শিক্ষায় সমান সুযোগ' মিশনে ১৫৮ বছর ধরে কার্যকর। দান সংগ্রহ করে স্কুল পরিচালনায় অর্থায়ন করে। ১৪ এপ্রিল ২০১২-এ সংবিধান সংশোধন করে মা হারানো ছাত্রদেরও অন্তর্ভুক্ত করা হয়। আজ ডারুসশাফাকা এক বা উভয় অভিভাবক হারানো মেধাবী ছাত্রদের জন্য উন্নত ভবিষ্যত তৈরি করছে। এটি দশ বছর বয়স থেকে ৫ম শ্রেণি থেকে উচ্চ মাধ্যমিক শেষ পর্যন্ত পূর্ণ বৃত্তি ও বোর্ডিং প্রদান করে। বিশ্বমানের শিক্ষা পেয়ে, শিক্ষার্থীরা আত্মবিশ্বাসী, চিন্তাশীল, অনুসন্ধিৎসু ও সমাজের দায় সম্পন্ন ব্যক্তি হিসেবে নতুন জীবন শুরু করে।",
"aboutText": "সবাইকে স্বাগতম।\n\nআমাদের বিশ্বায়িত বিশ্বে, সব কিছু একই রকম হয়ে যাচ্ছে। এল সালভাদর থেকে জাপান, জর্ডান থেকে কেপ টাউন, একই ব্র্যান্ড, একই বাড়ি, একই গল্প, একই চিন্তাধারার মানুষরা আমাদের চারপাশে। এই চ্যানেলে, আমি চেষ্টা করি আপনি যে স্থানগুলোতে অদাচার ভাবের দেশের দেখা পান না, সেখানে বিভিন্নতা, স্থানীয় স্বাদ, রাস্তার খাবার, দেশের ইতিহাস, দূরবর্তী উপজাতি, দেশের উজ্জ্বল ও অন্ধকার দিক অন্বেষণ করতে। আপনাদের কারণে, আমি চ্যানেলের সমস্ত আয় ছাত্রवৃত্তিতে দিচ্ছি। রসিদও শেয়ার করি। এই চ্যানেল আমাদের সবার। তাই আমাকে অনুসরণ ও সমর্থন করতে চাইলে আমি খুশি হব।\n\nশুভেচ্ছা।"
},
"Polski": {
"code": "pl",
"autotranslate": "Automatyczne tłumaczenie wszystkich wpisów na język polski",
"originalLang": "Pokaż oryginalny język",
"translating": "Tłumaczenie...",
"search": "Wyszukaj tytuł",
"title": "Galaktyczny Przewodnik Fatih Koparan",
"about": "O nas",
"map": "Mapa",
"blog": "Blog",
"donate": "Przekaż darowiznę",
"donateText": "Towarzystwo Darüşşafaka zostało założone w 1863 roku w celu zapewnienia równych szans w edukacji uzdolnionym i potrzebującym dzieciom, które straciły ojców. Od tamtej pory działa z misją „Równych Szans w Edukacji”. Nasze 158-letnie towarzystwo zbiera fundusze poprzez darowizny na rzecz szkoły. 14 kwietnia 2012 r. zmieniono statut, aby objąć także uczniów, którzy stracili matki. Obecnie Darüşşafaka tworzy lepszą przyszłość dla utalentowanych dzieci, które straciły jednego lub oboje rodziców. Zaprasza uczniów od dziesiątego roku życia i przyznaje pełne stypendium oraz internat od piątej klasy do ukończenia szkoły średniej. Otrzymując edukację na światowym poziomie, uczniowie zaczynają nowe życie jako pewni siebie, myślący, dociekliwi i odpowiedzialni obywatele społeczeństwa.",
"aboutText": "Cześć wszystkim.\n\nW zglobalizowanym świecie wszystko staje się takie samo. Od Salwadoru przez Japonię, od Jordanii po Kapsztad – te same marki, te same domy, te same historie i ci sami myślący ludzie nas otaczają. Na tym kanale próbuję odkrywać różnice, lokalne smaki, jedzenie uliczne, historię państw, odległe plemiona i zarówno jasne, jak i ciemne strony krajów, które pozostają na obrzeżach tego unifikowanego świata. Dzięki wam cały dochód kanału przekazuję na stypendia dla studentów. Udostępniam również potwierdzenia wpłat. Ten kanał należy do nas wszystkich. Będę wdzięczny za obserwację i wsparcie.",
},
"Svenska": {
"code": "sv",
"autotranslate": "Översätt automatiskt alla poster till svenska",
"originalLang": "Visa originalspråk",
"translating": "Översätter...",
"search": "Sök titel",
"title": "Fatih Koparans galaxguide",
"about": "Om oss",
"map": "Karta",
"blog": "Blogg",
"donate": "Donera",
"donateText": "Darüşşafaka-sällskapet grundades 1863 med målet att ge jämlika utbildningsmöjligheter till begåvade barn i nöd som mist sina fäder. Sedan dess har föreningen verkat för missionen “Lika möjligheter i utbildning”. Vår 158‑åriga förening samlar in medel via donationer för att finansiera skolan. Den 14 april 2012 ändrades stadgarna för att också omfatta elever som förlorat sina mödrar. Idag skapar Darüşşafaka en bättre framtid för begåvade barn som mist en eller båda föräldrarna. Föreningen bjuder in elever från tio års ålder och erbjuder full stipendium och internat från femte klass till gymnasieexamen. Med tillgång till utbildning i världsklass kan studenter börja ett nytt liv som självsäkra, eftertänksamma, nyfikna och ansvarstagande individer.",
"aboutText": "Hej allihopa.\n\nI vår globaliserade värld börjar allt bli likadant. Från El Salvador till Japan, från Jordanien till Kapstaden, omges vi av samma märken, samma hus, samma berättelser och samma tänkande människor. På den här kanalen försöker jag utforska skillnaderna, lokala smaker, street food, ländernas historia, avlägsna stammar, liksom de ljusa och mörka sidorna av länder som befinner sig i utkanten av vår homogena värld. Tack vare er ger jag alla kanalens inkomster som stipendier till studenter. Jag delar också kvitton. Denna kanal tillhör oss alla. Jag skulle bli glad om ni följer och stöttar den.",
},
"Nederlands": {
"code": "nl",
"autotranslate": "Automatisch alle vermeldingen vertalen naar het Nederlands",
"originalLang": "Originele taal tonen",
"translating": "Vertalen...",
"search": "Zoek titel",
"title": "Fatih Koparans Galaxiegids",
"about": "Over",
"map": "Kaart",
"blog": "Blog",
"donate": "Doneren",
"donateText": "De Darüşşafaka‑Vereniging werd in 1863 opgericht met als doel gelijkwaardige onderwijskansen te bieden aan getalenteerde kinderen in armoede die hun vader hadden verloren. Sindsdien zet de vereniging zich in voor de missie 'Gelijke Onderwijskansen'. Onze 158‑jarige vereniging werft via donaties financiering voor de school. Op 14 april 2012 werd het statuut gewijzigd om ook leerlingen te accepteren die hun moeder hadden verloren. Tegenwoordig creëert Darüşşafaka een betere toekomst voor getalenteerde kinderen die één of beide ouders hebben verloren. Vanaf hun tiende jaar nodigt de vereniging leerlingen uit en biedt volledige beurzen en internaten vanaf groep 5 tot het einde van de middelbare school. Met toegang tot onderwijs van wereldklasse kunnen studenten een nieuw leven beginnen als zelfverzekerde, denkwijzen, nieuwsgierige en maatschappelijk verantwoordelijk individuen.",
"aboutText": "Hallo allemaal.\n\nIn onze geglobaliseerde wereld wordt alles steeds hetzelfde. Van El Salvador tot Japan, van Jordanië tot Kaapstad: we worden omringd door dezelfde merken, dezelfde huizen, dezelfde verhalen en dezelfde nadenkende mensen. Op dit kanaal probeer ik de verschillen, lokale smaken, streetfood, de geschiedenis van landen, verre stammen en zowel de lichte als de donkere kanten van landen te ontdekken die aan de rand van onze homogene wereld blijven. Dankzij jullie geef ik alle inkomsten van het kanaal als beurzen aan studenten. Ik deel ook de bewijsstukken. Dit kanaal is van ons allemaal. Ik zou het op prijs stellen als je volgt en ondersteunt.",
},
"ภาษาไทย": {
"code": "th",
"autotranslate": "แปลรายการทั้งหมดเป็นภาษาไทยโดยอัตโนมัติ",
"originalLang": "แสดงภาษาต้นฉบับ",
"translating": "กำลังแปล...",
"search": "ค้นหาชื่อเรื่อง",
"title": "คู่มือกาแล็กซีของฟาติห์ โคพาราน",
"about": "เกี่ยวกับ",
"map": "แผนที่",
"blog": "บล็อก",
"donate": "บริจาค",
"donateText": "สมาคมดารูชชาฟากาก่อตั้งขึ้นในปี พ.ศ. 2406 โดยมีเป้าหมายเพื่อมอบโอกาสทางการศึกษาที่เท่าเทียมให้กับเด็กที่ยากจนและมีพรสวรรค์ที่สูญเสียพ่อไป นับตั้งแต่นั้นมา สมาคมได้ปฏิบัติภารกิจในการสร้างความเท่าเทียมทางการศึกษาเป็นเวลากว่า 158 ปี วันที่ 14 เมษายน 2555 ได้มีการแก้ไขข้อบังคับเพื่อให้สามารถรับนักเรียนที่สูญเสียแม่ได้เช่นกัน ปัจจุบัน ดารูชชาฟากาให้การศึกษาแบบทุนเต็มจำนวนแก่เด็กที่สูญเสียพ่อหรือแม่หรือทั้งสองคน ตั้งแต่อายุ 10 ปี (ชั้น ป.5) จนถึงจบมัธยมศึกษาตอนปลาย พร้อมที่พักและการศึกษาระดับโลกเพื่อสร้างอนาคตที่สดใสให้กับพวกเขา",
"aboutText": "สวัสดีทุกคน\n\nในโลกที่โลกาภิวัตน์ ทุกอย่างเริ่มเหมือนกันหมด ตั้งแต่เอลซัลวาดอร์ถึงญี่ปุ่น จากจอร์แดนถึงเคปทาวน์ เราถูกห้อมล้อมด้วยแบรนด์เดียวกัน บ้านแบบเดียวกัน เรื่องราวแบบเดียวกัน ผู้คนที่มีความคิดคล้ายกัน ในช่องนี้ ผมพยายามสำรวจความแตกต่าง กลิ่นอายท้องถิ่น อาหารริมทาง ประวัติศาสตร์ชนชาติ ชนเผ่าห่างไกล รวมถึงด้านสว่างและมืดของประเทศต่าง ๆ\n\nด้วยความช่วยเหลือจากคุณ รายได้จากช่องนี้ทั้งหมดจะถูกนำไปมอบเป็นทุนการศึกษาให้กับนักเรียน และผมจะแชร์ใบเสร็จให้ทุกคนดู ช่องนี้เป็นของพวกเราทุกคน หากคุณติดตามและสนับสนุน จะเป็นเกียรติอย่างยิ่ง\n\nขอบคุณครับ"
},
"Norsk": {
"code": "no",
"autotranslate": "Oversett alle oppføringer automatisk til norsk",
"originalLang": "Vis originalspråk",
"translating": "Oversetter...",
"search": "Søk etter tittel",
"title": "Fatih Koparans galakseguide",
"about": "Om",
"map": "Kart",
"blog": "Blogg",
"donate": "Doner",
"donateText": "Darüşşafaka-foreningen ble grunnlagt i 1863 med mål om å tilby like utdanningsmuligheter til talentfulle og trengende barn som har mistet faren sin. Foreningen har i 158 år jobbet med misjonen om «like muligheter i utdanning». Den 14. april 2012 ble vedtektene endret for også å inkludere barn som har mistet moren. I dag gir Darüşşafaka et bedre framtidshåp til begavede barn som har mistet én eller begge foreldre. Foreningen tilbyr fullt stipend og internat for elever fra 10 års alder (5. klasse) til de fullfører videregående skole, med utdanning på verdensnivå.",
"aboutText": "Hei alle sammen\n\nI en globalisert verden begynner alt å ligne på hverandre. Fra El Salvador til Japan, fra Jordan til Cape Town – vi er omgitt av de samme merkene, de samme husene, de samme historiene og de samme tenkende menneskene. På denne kanalen prøver jeg å utforske forskjellene som gjenstår: lokale smaker, gatemat, nasjoners historie, fjerne stammer og både de lyse og mørke sidene av ulike land.\n\nTakket være dere går alle inntektene fra kanalen til stipend for studenter, og jeg deler kvitteringer åpent. Denne kanalen tilhører oss alle. Jeg blir glad hvis du følger og støtter den.\n\nTusen takk"
}
};
